### ISSUE TITLE
Possible error in GithubPRPoller

### ISSUE THREAD

**Issue by fsaintjacques** [ursa-labs/ursabot#41]
```
2019-04-30 13:40:33-0500 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] while polling for changes
        Traceback (most recent call last):
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/changes/github.py", line 272, in poll
            yield self._processChanges(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/changes/github.py", line 272, in poll
            yield self._processChanges(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/changes/github.py", line 200, in _processChanges
            base_branch = pr['base']['ref']
        builtins.TypeError: string indices must be integers
```

**Comment by fsaintjacques** [comment]
This was related to an invalid token.
