### ISSUE TITLE
GitHuBStatusPush failure

### ISSUE THREAD

**Issue by fsaintjacques** [ursa-labs/ursabot#42]
```
2019-04-30 14:27:41-0500 [-] Stopping container d5b04a...
2019-04-30 14:27:41-0500 [-] while invoking <bound method HttpStatusPushBase.buildFinished of <buildbot.reporters.github.GitHubStatusPush object at 0x7f12d26e6e80>>
        Traceback (most recent call last):
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
            yield self.send(build)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
            yield self.send(build)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/reporters/github.py", line 143, in send
            repoOwner = giturl.owner
        builtins.AttributeError: 'NoneType' object has no attribute 'owner'
```

**Comment by fsaintjacques** [comment]
Related to invalid token.
