### ISSUE TITLE
Fix logging in SetPropertiesFromEnv

### ISSUE THREAD

**Issue by kszucs** [ursa-labs/ursabot#55]
```
2019-05-02 14:19:52-0500 [-] Got fatal Exception on DB
        Traceback (most recent call last):
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/db/pool.py", line 209, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/db/pool.py", line 182, in __thd
            rv = callable(arg, *args, **kwargs)
          File "/home/buildbot/.conda/envs/master/lib/python3.7/site-packages/buildbot/db/logs.py", line 156, in thdAddLog
            "log with slug '%r' already exists in this step" % (slug,))
        builtins.KeyError: "log with slug ''set-prop_3'' already exists in this step"
```

probably cause by https://github.com/ursa-labs/ursabot/blob/master/ursabot/steps.py#L140

**Comment by kszucs** [comment]
fixed by #57
